### ISSUE TITLE
DeepTIO pretrain models

### ISSUE THREAD

**Issue by chenxingxin-star** [MAPS-Lab/OdomBeyondVision#1]
Hi, thank you for sharing your dataset!
But the deeptio pretrain model link is the dataset link, could you provide the pretrain models?
thanks

**Comment by lipeize-pku** [comment]
Hi there, thanks for your interest in our dataset.
Pretrain model link has been fixed. It now shares the same folder as the dataset.

And are you one of the authors of _Thermal Inertial SLAM for Environments with Challenging Illumination_? The model presented in this submission is quite remarkable. We very much welcome the model as one of our thermal benchmarks in our dataset. What is your contact information? You can email me at lipeize.pku@gmail.com
