### ISSUE TITLE
Question about ground truth coordinate.

### ISSUE THREAD

**Issue by LilyGinger** [MAPS-Lab/OdomBeyondVision#2]
Hi, thanks for your great works! 
We are wondering if the odometry ground truth in UGV sequence is relative to the beginning of the sequence or to a fixed point in the building so that all sequences have the same ground truth coordinate.
Thanks for your time!

**Comment by li-peize** [comment]
Hi there, thanks for raising the issue.
The UGV sequences do not have a fixed origin for ground truth. They use the beginning of each sequence as origin. Same goes for handheld sequences.
The ground truth for UAV sequences does share a fixed origin in the Vicon system.

**Comment by LilyGinger** [comment]
Thanks a lot!
