### ISSUE TITLE
Failure of generating the model

### ISSUE THREAD

**Issue by GuoHeyu** [MAPS-Lab/OdomBeyondVision#8]
Hi author. Thanks for your excellent work. When I tried to generate the models, I found some problems.
After I put a picture of size 64 * 256 * 6 into the FlowNetModule, the output size is 1 * 4 * 1024. But the visual mask has a size of 1*1*1024, so the model fails to generate. Does it a bug in the code?

**Comment by li-peize** [comment]
I assume you are testing milliEgo?
We have different platforms in this dataset, some platforms might have different radar configurations and preprocessing settings, resulting in the radar depth image to be different sizes. You can change the mask size accordingly.

**Comment by GuoHeyu** [comment]
Thanks for your reply. I'm testing milliEgo indeed. Also I want to know if the IMU length of pretrained model is fixed to 20 because it reports error when I try different IMU length.

**Comment by li-peize** [comment]
You can change IMU length, but your data has to match your model. If your model is trained to take 20 IMU measurements at a time, then you need to feed it 20 IMU measurements for each prediction.
