### ISSUE TITLE
Radar data information

### ISSUE THREAD

**Issue by LilyGinger** [MAPS-Lab/OdomBeyondVision#9]
Hi, thanks for your dataset! 
We are wondering what is the difference between topic /mmWaveDataHdl/RScan_left, /mmWaveDataHdl/RScan_left_range, /mmWaveDataHdl/RScan_left_scan. We find that the "RScan_left" and "RScan_left_range" are PointCloud2 format, and the data fields are "x, y, z, intensity“. Does the "x, y, z, intensity" means the location and intensity of the radar points?

**Comment by LilyGinger** [comment]
By the way, seems that for the “/mmWaveDataHdl/RScan_left_scan” topic, one message denotes one point. Is there anyway to analyze the all point to pointclouds frame by frame.
Thanks a lot!

**Comment by LilyGinger** [comment]
By the way, seems that for the “/mmWaveDataHdl/RScan_left_scan” topic, one message denotes one point. Is there any method to analyze the all point to pointclouds frame by frame.
Thanks a lot!

**Comment by LilyGinger** [comment]
Hi, I find the ti_mmwave_pkg topic definition [https://github.com/radar-lab/ti_mmwave_rospkg]. However, I'm still confused with the message about how to integrate the messages into frames of radar point clouds.

**Comment by li-peize** [comment]
Hi there, thanks for checking out our dataset!
'/mmWaveDataHdl/RScan_left' is the correct topic for the PointCloud2 data. The data fields are indeed "x, y, z, intensity".
You can use our data extraction script to extract PointCloud2 data. Specifically, it happens in [this line of code](https://github.com/MAPS-Lab/OdomBeyondVision/blob/fa7e4f6e137458ea9abc8d10c3a11cb6991f87bf/toolkit/extract_rosbag/extract_files.py#L133).

**Comment by LilyGinger** [comment]
Hi, sorry for missing this information! Thanks for your reply!

**Comment by LilyGinger** [comment]
Hi, sorry for bothering you again.
I use the [extract_files.py](https://github.com/MAPS-Lab/OdomBeyondVision/blob/main/toolkit/extract_rosbag/extract_files.py) for  extracting the rosbag. The radar data are recorded as many "xxxxx.mat" file in 'mmwave_xxx_pcl' folder. Each "xxxxx.mat" file is a n*4 array. Is that "x,y,z,v" data of a frame of point cloud? If so, I find the last column of data a little strange as follows:

![image](https://user-images.githubusercontent.com/44052488/222873218-ba538640-2e46-4cfd-97fc-cc4e7a33ad03.png)

The v values are very large. Do I miss something?

**Comment by li-peize** [comment]
Hi there, I believe the 4th column is intensity, not velocity.
The data was recorded long ago using an old version of TI ROS driver. It didn't record velocity measurements at the time.

**Comment by LilyGinger** [comment]
Thanks. Seems that  the topic "/mmWaveDataHdl/RScan_left_scan" contains velocity information for each point. Is this information usable? 

![image](https://user-images.githubusercontent.com/44052488/223772943-01c49b84-2f24-4429-88a1-0894725b4100.png)

**Comment by li-peize** [comment]
Hi there, I don't think this field is very useful or very accurate. If you are using the data for publication purposes, we might be able to share some more recent data with proper velocity. You can contact me at peize.li@ed.ac.uk.
